<?php
declare(strict_types=1);

namespace Panth\XmlSitemap\Model\Sitemap;

class XslStylesheet
{
    public function getStylesheet(): string
    {
        return <<<'XSL'
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
    xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">

  <xsl:output method="html" indent="yes" encoding="UTF-8"/>

  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>XML Sitemap</title>
        <style>
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
                         Oxygen, Ubuntu, Cantarell, sans-serif;
            background: #f5f7fa;
            color: #333;
            padding: 20px;
          }
          h1 {
            font-size: 1.5rem;
            margin-bottom: 8px;
            color: #1a1a2e;
          }
          p.meta {
            font-size: 0.85rem;
            color: #666;
            margin-bottom: 20px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            background: #fff;
            border-radius: 6px;
            overflow: hidden;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
          }
          th {
            background: #1a1a2e;
            color: #fff;
            text-align: left;
            padding: 12px 16px;
            font-size: 0.8rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
          }
          td {
            padding: 10px 16px;
            border-bottom: 1px solid #eee;
            font-size: 0.85rem;
            vertical-align: top;
          }
          tr:last-child td { border-bottom: none; }
          tr:hover td { background: #f0f4ff; }
          td a { color: #2563eb; text-decoration: none; word-break: break-all; }
          td a:hover { text-decoration: underline; }
          .priority { text-align: center; }
          .changefreq { text-align: center; }
        </style>
      </head>
      <body>
        <h1>XML Sitemap</h1>
        <p class="meta">
          Generated by Panth XmlSitemap &#8212;
          <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs
        </p>

        <xsl:choose>
          <!-- Sitemap Index -->
          <xsl:when test="sitemap:sitemapindex">
            <table>
              <thead>
                <tr>
                  <th>Sitemap URL</th>
                  <th>Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                  <tr>
                    <td>
                      <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                    </td>
                    <td><xsl:value-of select="sitemap:lastmod"/></td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:when>

          <!-- URL Set -->
          <xsl:otherwise>
            <table>
              <thead>
                <tr>
                  <th>URL</th>
                  <th>Last Modified</th>
                  <th class="changefreq">Change Frequency</th>
                  <th class="priority">Priority</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                  <tr>
                    <td>
                      <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                    </td>
                    <td><xsl:value-of select="sitemap:lastmod"/></td>
                    <td class="changefreq"><xsl:value-of select="sitemap:changefreq"/></td>
                    <td class="priority"><xsl:value-of select="sitemap:priority"/></td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:otherwise>
        </xsl:choose>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
XSL;
    }
}
