<?php
declare(strict_types=1);

namespace Panth\XmlSitemap\Setup\Patch\Data;

use Magento\Framework\App\ResourceConnection;
use Magento\Framework\Setup\Patch\DataPatchInterface;
use Magento\Store\Model\StoreManagerInterface;

class InstallSitemapUrlRewrite implements DataPatchInterface
{
    private const REQUEST_PATH = 'panth-sitemap.xml';
    private const TARGET_PATH  = 'xml_sitemap/sitemap/index';

    public function __construct(
        private readonly ResourceConnection $resource,
        private readonly StoreManagerInterface $storeManager
    ) {
    }

    public function apply(): self
    {
        $connection = $this->resource->getConnection();
        $table = $this->resource->getTableName('url_rewrite');
        if (!$connection->isTableExists($table)) {
            return $this;
        }

        foreach ($this->storeManager->getStores(true) as $store) {
            $storeId = (int) $store->getId();
            $exists = (int) $connection->fetchOne(
                $connection->select()
                    ->from($table, 'COUNT(*)')
                    ->where('store_id = ?', $storeId)
                    ->where('request_path = ?', self::REQUEST_PATH)
            );
            if ($exists > 0) {
                continue;
            }
            $connection->insert($table, [
                'entity_type'      => 'custom',
                'entity_id'        => 0,
                'request_path'     => self::REQUEST_PATH,
                'target_path'      => self::TARGET_PATH,
                'redirect_type'    => 0,
                'store_id'         => $storeId,
                'description'      => 'Panth_XmlSitemap dynamic panth-sitemap.xml',
                'is_autogenerated' => 1,
                'metadata'         => null,
            ]);
        }

        return $this;
    }

    public static function getDependencies(): array
    {
        return [];
    }

    public function getAliases(): array
    {
        return [];
    }
}
