<?php
declare(strict_types=1);

namespace Panth\XmlSitemap\Model\Sitemap\Contributor;

use Magento\Framework\App\ResourceConnection;
use Magento\Store\Model\StoreManagerInterface;
use Panth\XmlSitemap\Api\ContributorInterface;

class CategoryContributor implements ContributorInterface
{
    public function __construct(
        private readonly ResourceConnection $resource,
        private readonly StoreManagerInterface $storeManager
    ) {
    }

    public function getCode(): string
    {
        return 'category';
    }

    public function getUrls(int $storeId, array $config = []): \Generator
    {
        $store   = $this->storeManager->getStore($storeId);
        $baseUrl = rtrim((string) $store->getBaseUrl(), '/') . '/';

        $conn     = $this->resource->getConnection();
        $urlTable = $this->resource->getTableName('url_rewrite');

        $excludeNoindex = isset($config['exclude_noindex'])
            ? (bool) $config['exclude_noindex']
            : false;

        $select = $conn->select()
            ->from(['ur' => $urlTable], ['request_path', 'entity_id'])
            ->where('ur.entity_type = ?', 'category')
            ->where('ur.store_id = ?', $storeId)
            ->where('ur.redirect_type = ?', 0)
            ->where('ur.is_autogenerated = ?', 1);

        if ($excludeNoindex) {
            $resolvedTable = $this->resource->getTableName('panth_seo_resolved');
            $select->joinLeft(
                ['seo' => $resolvedTable],
                "seo.entity_type = 'category' AND seo.entity_id = ur.entity_id AND seo.store_id IN (0, {$storeId})",
                []
            );
            $select->where('seo.robots IS NULL OR seo.robots NOT LIKE ?', '%noindex%');
        }

        $changefreq = $config['changefreq'] ?? 'weekly';
        $priority   = isset($config['priority']) ? (float) $config['priority'] : 0.7;

        $stmt = $conn->query($select);
        while ($row = $stmt->fetch(\PDO::FETCH_ASSOC)) {
            $path = (string) ($row['request_path'] ?? '');
            if ($path === '') {
                continue;
            }
            yield [
                'loc'        => $baseUrl . ltrim($path, '/'),
                'changefreq' => $changefreq,
                'priority'   => $priority,
            ];
        }
    }
}
