<?php
declare(strict_types=1);

namespace Panth\XmlSitemap\Model\Sitemap\Contributor;

use Magento\Framework\App\ResourceConnection;
use Magento\Store\Model\StoreManagerInterface;
use Panth\XmlSitemap\Api\ContributorInterface;

class CategoryContributor implements ContributorInterface
{
    /** @var array<string, int> Memoised catalog_category attribute_id lookups. */
    private array $categoryAttributeIds = [];

    public function __construct(
        private readonly ResourceConnection $resource,
        private readonly StoreManagerInterface $storeManager
    ) {
    }

    public function getCode(): string
    {
        return 'category';
    }

    public function getUrls(int $storeId, array $config = []): \Generator
    {
        $store   = $this->storeManager->getStore($storeId);
        $baseUrl = rtrim((string) $store->getBaseUrl(), '/') . '/';

        $conn       = $this->resource->getConnection();
        $urlTable   = $this->resource->getTableName('url_rewrite');
        $catTable   = $this->resource->getTableName('catalog_category_entity');
        $catIntTbl  = $this->resource->getTableName('catalog_category_entity_int');
        $rootCatId  = (int) $store->getRootCategoryId();

        $excludeNoindex = isset($config['exclude_noindex'])
            ? (bool) $config['exclude_noindex']
            : false;

        $select = $conn->select()
            ->from(['ur' => $urlTable], ['request_path', 'entity_id'])
            ->joinInner(
                ['cce' => $catTable],
                'cce.entity_id = ur.entity_id',
                ['category_updated_at' => 'cce.updated_at']
            )
            ->where('ur.entity_type = ?', 'category')
            ->where('ur.store_id = ?', $storeId)
            ->where('ur.redirect_type = ?', 0)
            ->where('ur.is_autogenerated = ?', 1);

        // Skip the store root and anything outside its subtree. The root has
        // no public URL of its own and Magento doesn't render listing pages
        // for siblings of the active root.
        $select->where('cce.path LIKE ?', '1/' . $rootCatId . '/%');

        // Inactive categories keep their url_rewrite rows after being toggled
        // off, so we must filter the EAV `is_active` flag with the standard
        // store-scoped + admin-fallback pattern.
        $isActiveAttrId = $this->resolveCategoryAttributeId('is_active');
        if ($isActiveAttrId > 0) {
            $select->joinLeft(
                ['act_admin' => $catIntTbl],
                'act_admin.entity_id = ur.entity_id'
                . ' AND act_admin.attribute_id = ' . $isActiveAttrId
                . ' AND act_admin.store_id = 0',
                []
            )->joinLeft(
                ['act_store' => $catIntTbl],
                'act_store.entity_id = ur.entity_id'
                . ' AND act_store.attribute_id = ' . $isActiveAttrId
                . ' AND act_store.store_id = ' . $storeId,
                []
            )->where('COALESCE(act_store.value, act_admin.value) = ?', 1);
        }

        if ($excludeNoindex) {
            $resolvedTable = $this->resource->getTableName('panth_seo_resolved');
            $select->joinLeft(
                ['seo' => $resolvedTable],
                "seo.entity_type = 'category' AND seo.entity_id = ur.entity_id AND seo.store_id IN (0, {$storeId})",
                []
            );
            $select->where('seo.robots IS NULL OR seo.robots NOT LIKE ?', '%noindex%');
        }

        $changefreq = $config['changefreq'] ?? 'weekly';
        $priority   = isset($config['priority']) ? (float) $config['priority'] : 0.7;

        $stmt = $conn->query($select);
        while ($row = $stmt->fetch(\PDO::FETCH_ASSOC)) {
            $path = (string) ($row['request_path'] ?? '');
            if ($path === '') {
                continue;
            }
            $entry = [
                'loc'        => $baseUrl . ltrim($path, '/'),
                'changefreq' => $changefreq,
                'priority'   => $priority,
            ];

            // Per-row <lastmod> from catalog_category_entity.updated_at.
            $updatedAt = (string) ($row['category_updated_at'] ?? '');
            if ($updatedAt !== '') {
                try {
                    $entry['lastmod'] = (new \DateTimeImmutable($updatedAt))
                        ->format('Y-m-d\TH:i:sP');
                } catch (\Throwable) {
                    // Skip lastmod rather than emit garbage.
                }
            }

            yield $entry;
        }
    }

    /**
     * Resolve a catalog_category EAV attribute_id by code, memoised.
     */
    private function resolveCategoryAttributeId(string $code): int
    {
        if (array_key_exists($code, $this->categoryAttributeIds)) {
            return $this->categoryAttributeIds[$code];
        }
        $conn = $this->resource->getConnection();
        $eavTable = $this->resource->getTableName('eav_attribute');
        $entityTypeTable = $this->resource->getTableName('eav_entity_type');
        $sql = sprintf(
            'SELECT ea.attribute_id FROM %s AS ea'
            . ' INNER JOIN %s AS et ON et.entity_type_id = ea.entity_type_id'
            . ' WHERE et.entity_type_code = %s AND ea.attribute_code = %s LIMIT 1',
            $conn->quoteIdentifier($eavTable),
            $conn->quoteIdentifier($entityTypeTable),
            $conn->quote('catalog_category'),
            $conn->quote($code)
        );
        return $this->categoryAttributeIds[$code] = (int) $conn->fetchOne($sql);
    }
}
