<?php
declare(strict_types=1);

namespace Panth\XmlSitemap\Model\Sitemap\Contributor;

use Magento\Framework\App\ResourceConnection;
use Magento\Store\Model\StoreManagerInterface;
use Panth\Hreflang\Api\HreflangResolverInterface;
use Panth\AdvancedSEO\Helper\Config as AdvancedSeoConfig;
use Panth\XmlSitemap\Api\ContributorInterface;
use Panth\XmlSitemap\Helper\Config;

/**
 * Streams product + category URLs with hreflang <xhtml:link> alternates.
 * Uses HreflangResolverInterface to look up the alternate set per entity.
 *
 * NOTE: When enabled, disable Product/Category contributors to avoid
 * duplicate <url> entries (hreflang wraps the same locs).
 */
class HreflangContributor implements ContributorInterface
{
    public function __construct(
        private readonly ResourceConnection $resource,
        private readonly StoreManagerInterface $storeManager,
        private readonly HreflangResolverInterface $hreflangResolver,
        private readonly Config $config,
        private readonly AdvancedSeoConfig $advancedSeoConfig
    ) {
    }

    public function getCode(): string
    {
        return 'hreflang';
    }

    public function getUrls(int $storeId, array $config = []): \Generator
    {
        if (!$this->config->sitemapIncludeHreflang($storeId) || !$this->advancedSeoConfig->isHreflangEnabled($storeId)) {
            return;
        }
        $store   = $this->storeManager->getStore($storeId);
        $baseUrl = rtrim((string) $store->getBaseUrl(), '/') . '/';

        $conn     = $this->resource->getConnection();
        $urlTable = $this->resource->getTableName('url_rewrite');

        foreach (['product', 'category'] as $type) {
            $select = $conn->select()
                ->from($urlTable, ['entity_id', 'request_path'])
                ->where('entity_type = ?', $type)
                ->where('store_id = ?', $storeId)
                ->where('redirect_type = ?', 0)
                ->where('is_autogenerated = ?', 1);

            $stmt = $conn->query($select);
            while ($row = $stmt->fetch(\PDO::FETCH_ASSOC)) {
                $id   = (int) $row['entity_id'];
                $path = (string) $row['request_path'];
                if ($id <= 0 || $path === '') {
                    continue;
                }
                $alts = $this->hreflangResolver->getAlternates($type, $id, $storeId);
                $hreflang = [];
                foreach ($alts as $alt) {
                    $locale = (string) ($alt['locale'] ?? '');
                    $altUrl = (string) ($alt['url'] ?? '');
                    if ($locale === '' || $altUrl === '') {
                        continue;
                    }
                    $hreflang[] = [
                        'locale' => $locale,
                        'url'    => $altUrl,
                    ];
                }
                yield [
                    'loc'        => $baseUrl . ltrim($path, '/'),
                    'changefreq' => 'weekly',
                    'priority'   => $type === 'product' ? 0.8 : 0.7,
                    'hreflang'   => $hreflang,
                ];
            }
        }
    }
}
