<?php
declare(strict_types=1);

namespace Panth\XmlSitemap\Model\Sitemap\Contributor;

use Magento\Catalog\Helper\Image as ImageHelper;
use Magento\Catalog\Model\Product;
use Magento\Catalog\Model\Product\Attribute\Source\Status as ProductStatus;
use Magento\Catalog\Model\Product\Visibility as ProductVisibility;
use Magento\Catalog\Model\ResourceModel\Product\CollectionFactory as ProductCollectionFactory;
use Magento\Framework\App\ResourceConnection;
use Magento\Store\Model\StoreManagerInterface;
use Panth\XmlSitemap\Api\ContributorInterface;

/**
 * Streams product URLs and attaches image:image entries for each product
 * (up to N media gallery images). Batches product collection so memory
 * stays bounded.
 *
 * NOTE: When enabled, disable ProductContributor to avoid duplicate <url>
 * entries — this contributor already emits the same product loc with images.
 */
class ImageContributor implements ContributorInterface
{
    private const BATCH = 500;
    private const MAX_IMAGES_PER_URL = 5;

    public function __construct(
        private readonly ResourceConnection $resource,
        private readonly StoreManagerInterface $storeManager,
        private readonly ProductCollectionFactory $productCollectionFactory,
        private readonly ImageHelper $imageHelper
    ) {
    }

    public function getCode(): string
    {
        return 'image';
    }

    public function getUrls(int $storeId, array $config = []): \Generator
    {
        $store   = $this->storeManager->getStore($storeId);
        $baseUrl = rtrim((string) $store->getBaseUrl(), '/') . '/';

        // Get list of product IDs + URL paths first via url_rewrite
        $conn     = $this->resource->getConnection();
        $urlTable = $this->resource->getTableName('url_rewrite');

        $select = $conn->select()
            ->from($urlTable, ['entity_id', 'request_path'])
            ->where('entity_type = ?', 'product')
            ->where('store_id = ?', $storeId)
            ->where('redirect_type = ?', 0)
            ->where('is_autogenerated = ?', 1);

        $stmt = $conn->query($select);

        $batchIds = [];
        $batchMeta = [];
        while ($row = $stmt->fetch(\PDO::FETCH_ASSOC)) {
            $id   = (int) $row['entity_id'];
            $path = (string) $row['request_path'];
            if ($id <= 0 || $path === '') {
                continue;
            }
            $batchIds[] = $id;
            $batchMeta[$id] = $path;
            if (count($batchIds) >= self::BATCH) {
                yield from $this->emitBatch($batchIds, $batchMeta, $storeId, $baseUrl);
                $batchIds = [];
                $batchMeta = [];
            }
        }
        if (!empty($batchIds)) {
            yield from $this->emitBatch($batchIds, $batchMeta, $storeId, $baseUrl);
        }
    }

    /**
     * @param int[] $ids
     * @param array<int,string> $meta
     */
    private function emitBatch(array $ids, array $meta, int $storeId, string $baseUrl): \Generator
    {
        $collection = $this->productCollectionFactory->create();
        $collection->setStoreId($storeId)
            ->addAttributeToSelect(['name', 'image'])
            ->addFieldToFilter('entity_id', ['in' => $ids])
            // url_rewrite outlives status / visibility / website unassignment,
            // so the same filters the native sitemap applies need to apply
            // here too — otherwise disabled or de-listed products leak in.
            ->addAttributeToFilter('status', ProductStatus::STATUS_ENABLED)
            ->setVisibility([
                ProductVisibility::VISIBILITY_IN_CATALOG,
                ProductVisibility::VISIBILITY_BOTH,
            ])
            ->addWebsiteFilter((int) $this->storeManager->getStore($storeId)->getWebsiteId())
            ->addMediaGalleryData();

        /** @var Product $product */
        foreach ($collection as $product) {
            $id = (int) $product->getId();
            if (!isset($meta[$id])) {
                continue;
            }
            $images = [];
            $gallery = $product->getMediaGalleryImages();
            if ($gallery) {
                $i = 0;
                foreach ($gallery as $img) {
                    $loc = (string) $img->getUrl();
                    if ($loc === '') {
                        continue;
                    }
                    $entry = ['loc' => $loc];
                    $label = (string) ($img->getLabel() ?: $product->getName());
                    if ($label !== '') {
                        $entry['caption'] = $label;
                        $entry['title']   = $label;
                    }
                    $images[] = $entry;
                    if (++$i >= self::MAX_IMAGES_PER_URL) {
                        break;
                    }
                }
            }
            yield [
                'loc'        => $baseUrl . ltrim($meta[$id], '/'),
                'changefreq' => 'weekly',
                'priority'   => 0.8,
                'images'     => $images,
            ];
        }
        $collection->clear();
    }
}
