<?php
declare(strict_types=1);

namespace Panth\XmlSitemap\Model\Sitemap\Contributor;

use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\App\ResourceConnection;
use Magento\Store\Model\ScopeInterface;
use Magento\Store\Model\StoreManagerInterface;
use Panth\XmlSitemap\Api\ContributorInterface;

class VideoContributor implements ContributorInterface
{
    private const XML_INCLUDE_VIDEO = 'panth_xml_sitemap/media/include_video';

    public function __construct(
        private readonly ResourceConnection $resource,
        private readonly StoreManagerInterface $storeManager,
        private readonly ScopeConfigInterface $scopeConfig
    ) {
    }

    public function getCode(): string
    {
        return 'video';
    }

    public function getUrls(int $storeId, array $config = []): \Generator
    {
        if (!$this->scopeConfig->isSetFlag(self::XML_INCLUDE_VIDEO, ScopeInterface::SCOPE_STORE, $storeId)) {
            return;
        }

        $store   = $this->storeManager->getStore($storeId);
        $baseUrl = rtrim((string) $store->getBaseUrl(), '/') . '/';

        $conn = $this->resource->getConnection();

        $pdo = $conn->getConnection();

        $galleryTable      = $this->resource->getTableName('catalog_product_entity_media_gallery');
        $galleryValueTable = $this->resource->getTableName('catalog_product_entity_media_gallery_value');
        $videoTable        = $this->resource->getTableName('catalog_product_entity_media_gallery_value_video');
        $urlRewriteTable   = $this->resource->getTableName('url_rewrite');

        $sql = sprintf(
            'SELECT DISTINCT
                ur.request_path,
                v.url      AS video_url,
                v.title    AS video_title,
                v.description AS video_description,
                v.thumbnail AS video_thumbnail,
                mgv.label  AS video_label
            FROM %s AS mg
            INNER JOIN %s AS mgv
                ON mgv.value_id = mg.value_id
                AND mgv.store_id IN (0, %d)
            INNER JOIN %s AS v
                ON v.value_id = mg.value_id
                AND v.store_id IN (0, %d)
            INNER JOIN %s AS mgvte
                ON mgvte.value_id = mg.value_id
            INNER JOIN %s AS ur
                ON ur.entity_id = mgvte.entity_id
                AND ur.entity_type = %s
                AND ur.store_id = %d
                AND ur.redirect_type = 0
                AND ur.is_autogenerated = 1
            WHERE mg.media_type = %s
                AND v.url IS NOT NULL
                AND v.url != %s',
            $conn->quoteIdentifier($galleryTable),
            $conn->quoteIdentifier($galleryValueTable),
            $storeId,
            $conn->quoteIdentifier($videoTable),
            $storeId,
            $conn->quoteIdentifier(
                $this->resource->getTableName('catalog_product_entity_media_gallery_value_to_entity')
            ),
            $conn->quoteIdentifier($urlRewriteTable),
            $conn->quote('product'),
            $storeId,
            $conn->quote('external-video'),
            $conn->quote('')
        );

        if ($pdo instanceof \PDO) {
            try {
                $pdo->setAttribute(\PDO::MYSQL_ATTR_USE_BUFFERED_QUERY, false);
            } catch (\Throwable) {
            }
        }

        $stmt = $pdo instanceof \PDO ? $pdo->query($sql) : $conn->query($sql);
        if (!$stmt) {
            return;
        }

        try {
            $currentPath = null;
            $videos      = [];

            while ($row = $stmt->fetch(\PDO::FETCH_ASSOC)) {
                $path = (string) ($row['request_path'] ?? '');
                if ($path === '') {
                    continue;
                }

                if ($currentPath !== null && $currentPath !== $path) {
                    yield $this->buildEntry($baseUrl, $currentPath, $videos);
                    $videos = [];
                }

                $currentPath = $path;
                $videoUrl    = (string) ($row['video_url'] ?? '');
                if ($videoUrl === '') {
                    continue;
                }

                $videos[] = [
                    'content_loc'   => $videoUrl,
                    'title'         => (string) ($row['video_title'] ?? $row['video_label'] ?? ''),
                    'description'   => (string) ($row['video_description'] ?? ''),
                    'thumbnail_loc' => (string) ($row['video_thumbnail'] ?? ''),
                ];
            }

            if ($currentPath !== null && $videos !== []) {
                yield $this->buildEntry($baseUrl, $currentPath, $videos);
            }
        } finally {
            if ($pdo instanceof \PDO) {
                try {
                    $pdo->setAttribute(\PDO::MYSQL_ATTR_USE_BUFFERED_QUERY, true);
                } catch (\Throwable) {
                }
            }
        }
    }

    private function buildEntry(string $baseUrl, string $path, array $videos): array
    {
        return [
            'loc'        => $baseUrl . ltrim($path, '/'),
            'changefreq' => 'weekly',
            'priority'   => 0.8,
            'video'      => $videos,
        ];
    }
}
