<?php
declare(strict_types=1);

namespace Panth\XmlSitemap\Model\Sitemap\Contributor;

use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\App\ResourceConnection;
use Magento\Store\Model\ScopeInterface;
use Magento\Store\Model\StoreManagerInterface;
use Panth\XmlSitemap\Api\ContributorInterface;

class VideoContributor implements ContributorInterface
{
    private const XML_INCLUDE_VIDEO = 'panth_xml_sitemap/media/include_video';

    public function __construct(
        private readonly ResourceConnection $resource,
        private readonly StoreManagerInterface $storeManager,
        private readonly ScopeConfigInterface $scopeConfig
    ) {
    }

    public function getCode(): string
    {
        return 'video';
    }

    public function getUrls(int $storeId, array $config = []): \Generator
    {
        if (!$this->scopeConfig->isSetFlag(self::XML_INCLUDE_VIDEO, ScopeInterface::SCOPE_STORE, $storeId)) {
            return;
        }
        if (isset($config['include_video_sitemap']) && !$config['include_video_sitemap']) {
            return;
        }

        $store   = $this->storeManager->getStore($storeId);
        $baseUrl = rtrim(
            (string) $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK, $store->isUrlSecure()),
            '/'
        ) . '/';
        $mediaUrl = rtrim(
            (string) $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA, $store->isUrlSecure()),
            '/'
        ) . '/catalog/product/';

        $conn = $this->resource->getConnection();

        $pdo = $conn->getConnection();

        $galleryTable      = $this->resource->getTableName('catalog_product_entity_media_gallery');
        $galleryValueTable = $this->resource->getTableName('catalog_product_entity_media_gallery_value');
        $videoTable        = $this->resource->getTableName('catalog_product_entity_media_gallery_value_video');
        $urlRewriteTable   = $this->resource->getTableName('url_rewrite');
        $websiteTable      = $this->resource->getTableName('catalog_product_website');
        $intTable          = $this->resource->getTableName('catalog_product_entity_int');
        $statusAttrId      = (int) $conn->fetchOne(
            $conn->select()
                ->from(['ea' => $this->resource->getTableName('eav_attribute')], ['attribute_id'])
                ->join(
                    ['et' => $this->resource->getTableName('eav_entity_type')],
                    'et.entity_type_id = ea.entity_type_id',
                    []
                )
                ->where('et.entity_type_code = ?', 'catalog_product')
                ->where('ea.attribute_code = ?', 'status')
                ->limit(1)
        );

        $sql = sprintf(
            'SELECT DISTINCT
                ur.request_path,
                v.url      AS video_url,
                v.title    AS video_title,
                v.description AS video_description,
                mg.value   AS video_thumbnail,
                mgv.label  AS video_label
            FROM %s AS mg
            INNER JOIN %s AS mgv
                ON mgv.value_id = mg.value_id
                AND mgv.store_id IN (0, %d)
            INNER JOIN %s AS v
                ON v.value_id = mg.value_id
                AND v.store_id IN (0, %d)
            INNER JOIN %s AS mgvte
                ON mgvte.value_id = mg.value_id
            INNER JOIN %s AS ur
                ON ur.entity_id = mgvte.entity_id
                AND ur.entity_type = %s
                AND ur.store_id = %d
                AND ur.redirect_type = 0
                AND ur.is_autogenerated = 1
            INNER JOIN %s AS pw
                ON pw.product_id = ur.entity_id
                AND pw.website_id = %d
            LEFT JOIN %s AS status_admin
                ON status_admin.entity_id = ur.entity_id
                AND status_admin.attribute_id = %d
                AND status_admin.store_id = 0
            LEFT JOIN %s AS status_store
                ON status_store.entity_id = ur.entity_id
                AND status_store.attribute_id = %d
                AND status_store.store_id = %d
            WHERE mg.media_type = %s
                AND v.url IS NOT NULL
                AND v.url != %s
                AND COALESCE(status_store.value, status_admin.value) = 1
            ORDER BY ur.request_path',
            $conn->quoteIdentifier($galleryTable),
            $conn->quoteIdentifier($galleryValueTable),
            $storeId,
            $conn->quoteIdentifier($videoTable),
            $storeId,
            $conn->quoteIdentifier(
                $this->resource->getTableName('catalog_product_entity_media_gallery_value_to_entity')
            ),
            $conn->quoteIdentifier($urlRewriteTable),
            $conn->quote('product'),
            $storeId,
            $conn->quoteIdentifier($websiteTable),
            (int) $store->getWebsiteId(),
            $conn->quoteIdentifier($intTable),
            $statusAttrId,
            $conn->quoteIdentifier($intTable),
            $statusAttrId,
            $storeId,
            $conn->quote('external-video'),
            $conn->quote('')
        );

        if ($pdo instanceof \PDO) {
            try {
                $pdo->setAttribute(\PDO::MYSQL_ATTR_USE_BUFFERED_QUERY, false);
            } catch (\Throwable) {
            }
        }

        try {
            $stmt = $pdo instanceof \PDO ? $pdo->query($sql) : $conn->query($sql);
            if (!$stmt) {
                return;
            }
            $currentPath = null;
            $videos      = [];

            while ($row = $stmt->fetch(\PDO::FETCH_ASSOC)) {
                $path = (string) ($row['request_path'] ?? '');
                if ($path === '') {
                    continue;
                }

                if ($currentPath !== null && $currentPath !== $path) {
                    yield $this->buildEntry($baseUrl, $currentPath, $videos);
                    $videos = [];
                }

                $currentPath = $path;
                $videoUrl    = (string) ($row['video_url'] ?? '');
                if ($videoUrl === '') {
                    continue;
                }

                $title = trim((string) ($row['video_title'] ?? ''));
                if ($title === '') {
                    $title = trim((string) ($row['video_label'] ?? ''));
                }
                $videos[] = $this->resolveVideoLocation($videoUrl) + [
                    'title'         => $title,
                    'description'   => (string) ($row['video_description'] ?? ''),
                    'thumbnail_loc' => (string) ($row['video_thumbnail'] ?? '') !== ''
                        ? $mediaUrl . ltrim((string) $row['video_thumbnail'], '/')
                        : '',
                ];
            }

            if ($currentPath !== null && $videos !== []) {
                yield $this->buildEntry($baseUrl, $currentPath, $videos);
            }
        } finally {
            if ($pdo instanceof \PDO) {
                try {
                    $pdo->setAttribute(\PDO::MYSQL_ATTR_USE_BUFFERED_QUERY, true);
                } catch (\Throwable) {
                }
            }
        }
    }

    public function resolveVideoLocation(string $videoUrl): array
    {
        $videoUrl = trim($videoUrl);
        $parts    = parse_url($videoUrl);
        if (!is_array($parts) || empty($parts['host'])) {
            return ['player_loc' => $videoUrl];
        }
        $host = strtolower((string) $parts['host']);
        $path = (string) ($parts['path'] ?? '');

        if (preg_match('/\.(mp4|m4v|webm|ogv|ogg|mov|mpe?g|wmv|avi|flv|3gp|mkv)$/i', $path) === 1) {
            return ['content_loc' => $videoUrl];
        }

        $youtubeId = null;
        if ($host === 'youtu.be' || $host === 'www.youtu.be') {
            $youtubeId = trim($path, '/');
        } elseif (preg_match('/(^|\.)youtube(-nocookie)?\.com$/', $host) === 1) {
            if (preg_match('#^/(embed|shorts|v|live)/([^/?]+)#', $path, $m) === 1) {
                $youtubeId = $m[2];
            } else {
                parse_str((string) ($parts['query'] ?? ''), $query);
                $youtubeId = isset($query['v']) && is_string($query['v']) ? $query['v'] : null;
            }
        }
        if ($youtubeId !== null && preg_match('/^[A-Za-z0-9_-]{6,20}$/', $youtubeId) === 1) {
            return ['player_loc' => 'https://www.youtube.com/embed/' . $youtubeId];
        }

        if (preg_match('/(^|\.)vimeo\.com$/', $host) === 1
            && preg_match('#/(\d+)(?:/|$)#', $path, $m) === 1
        ) {
            return ['player_loc' => 'https://player.vimeo.com/video/' . $m[1]];
        }

        return ['player_loc' => $videoUrl];
    }

    private function buildEntry(string $baseUrl, string $path, array $videos): array
    {
        return [
            'loc'        => $baseUrl . ltrim($path, '/'),
            'changefreq' => 'weekly',
            'priority'   => 0.8,
            'video'      => $videos,
        ];
    }
}
